[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && gunicorn ems.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
